### ISSUE TITLE
Support importing VPC resource

### ISSUE THREAD

**Issue by QuantumGhost** [tencentyun/terraform-provider-tencentcloud#36]
Currently the provider does not support importing existing VPCs.
I hope that importing VPC could be supported so I can manage existing VPCs with terraform.

**Comment by athom** [comment]
Hi, @QuantumGhost thanks for the feedback, 
the importer feature is in the plan. coming soon.

**Comment by arielwq** [comment]
@athom I noticed your comment on this request 7 months ago. Is there any update on this? This is important for us to bring existing resources into terraform.

**Comment by likexian** [comment]
move to: https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/33

**Comment by likexian** [comment]
this will partially supported in next release. full supported is under development.
