### ISSUE TITLE
add resource sweeper to handle failed acc test

### ISSUE THREAD

**Issue by zqfan** [tencentyun/terraform-provider-tencentcloud#39]
when acc test fail it might cause resource not be deleted correctly, hence it will block subsequential acc test, we need to clean them in a right manner

**Comment by likexian** [comment]
Hello @zqfan 
Is there more information or case?

**Comment by likexian** [comment]
move to: https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/40
