### ISSUE TITLE
image_name_regex attribute of image get wrong result

### ISSUE THREAD

**Issue by jhsea3do** [tencentyun/terraform-provider-tencentcloud#70]
version = 1.2.1
I want to use CentOS 7.2  image,  then i set "image_name_regex" = "^CentOS\\s+7\\.2\\s+64\\w*",
but the instance still use CentOS 7.5 image.

my codes 
```ruby
# main.tf

data "tencentcloud_image" "my_favorate_image" {
  os_name = "${var.os_name}"
  image_name_regex = "${var.image_name_regex}"

  filter {
    name   = "image-type"
    values = ["PUBLIC_IMAGE"]
  }
}

resource "tencentcloud_instance" "node1" {
  image_id          = "${data.tencentcloud_image.my_favorate_image.image_id}"
}

# variables.tf 

variable "image_name_regex" {
  default = "^CentOS\\s+7\\.2\\s+64\\w*"
}
```

my plan json
```json
                        "attributes": {
                            "filter.#": "1",
                            "filter.2430114294.name": "image-type",
                            "filter.2430114294.values.#": "1",
                            "filter.2430114294.values.0": "PUBLIC_IMAGE",
                            "id": "1260844541",
                            "image_id": "img-oikl1tzv",
                            "image_name_regex": "^CentOS\\s+7\\.2\\s+64\\w*",
                            "os_name": "centos"
                        }
```

**Comment by zqfan** [comment]
@jhsea3do please check our source code or document inside website directory, the logic is 

* first of all, use filter to describe image list, 
* then if os_name is set, we try to find an image match it, 
* if os_name is not specified, we use regular expression to match it
* if no reg exp specified, we just use the first one

so in your case, you have specified os_name, we just use the first image which os_name is centos. If you want to exactly match the version you need, you should remove the os_name parameter, and use image_name_regex param.

**Comment by jhsea3do** [comment]
@zqfan    

Thank you! It works!
