### ISSUE TITLE
Support routing table and subnet binding

### ISSUE THREAD

**Issue by arielwq** [tencentyun/terraform-provider-tencentcloud#75]
Hi, I checked on the tencentcloud terraform provider documentation and don't see anything that allows binding of a subnet to a routing table. Can we add this support? Thanks.
https://www.terraform.io/docs/providers/tencentcloud/r/subnet.html

**Comment by hiscal2015** [comment]
Looks like it is there:
https://www.terraform.io/docs/providers/tencentcloud/r/subnet.html#route_table_id

Is this what you want?

**Comment by zqfan** [comment]
I will transfer this issue to terraform-providers/terraform-provider-tencentcloud

**Comment by likexian** [comment]
move to: https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/10

**Comment by likexian** [comment]
Hello @arielwq 
This is supported, please try the least version.
Any issue please submit to us.
