### ISSUE TITLE
[Feature request] add support CLOUD_PREMIUM system/data disks in instance resource

### ISSUE THREAD

**Issue by hiscal2015** [tencentyun/terraform-provider-tencentcloud#78]
Tencent cloud has deprecated CLOUD_BASIC as system disk, please add support CLOUD_PREMIUM as system/data disk type, thanks.

See:
https://github.com/tencentyun/terraform-provider-tencentcloud/pull/77

**Comment by likexian** [comment]
CLOUD_PREMIUM is supported, please refer to #77
